// Local-only browser QA: real app scripts, isolated in-memory account service.
const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..');const tables={user_settings:new Map(),user_app_state:new Map()};
tables.user_settings.set('existing',{user_id:'existing',currency:'RON',daily_allowance:75,daily_currency:'RON',baseline_burn:3000,horizon:12});
tables.user_app_state.set('existing',{user_id:'existing',revision:1,state:{transactions:[{id:'salary',name:'QA salary',type:'Income',cat:'Salary',amt:5000},{id:'food',name:'QA groceries',type:'Expense',cat:'Food',amt:-150}],scenario:{inc:31500,exp:15000,inv:1200,evt:2500},chart:'base',view:'dashboard',draft:{name:'',amount:'',type:'Expense',cat:'Food'}}});
function mockClient(){
 const id=new URLSearchParams(location.search).has('new')?'new-user':'existing';let user={id,email:id+'@preview.test'},callback;
 window.FINTRACK_CONFIG={supabaseUrl:'https://preview.supabase.co',supabasePublishableKey:'sb_publishable_preview'};
 window.supabase={createClient:()=>({auth:{onAuthStateChange(fn){callback=fn;setTimeout(()=>fn('INITIAL_SESSION',{user}),0);},async signOut(){user=null;callback('SIGNED_OUT',null);return {};},async signInWithPassword(){user={id,email:id+'@preview.test'};callback('SIGNED_IN',{user});return {};},async getSession(){return {data:{session:{user}}};}},from(table){let owner,payload,revision;const chain={select(){return chain;},eq(key,value){if(key==='user_id')owner=value;else revision=value;return chain;},upsert(v){payload=v;return chain;},insert(v){payload=v;return chain;},update(v){payload=v;return chain;},async maybeSingle(){return (await fetch('/qa-store?table='+table+'&owner='+owner)).json();},async single(){return (await fetch('/qa-store',{method:'POST',body:JSON.stringify({table,payload,revision})})).json();}};return chain;}})};
}
http.createServer(async(req,res)=>{const url=new URL(req.url,'http://127.0.0.1');res.setHeader('Cache-Control','no-store');if(url.pathname==='/qa-store'){res.setHeader('Content-Type','application/json');if(req.method==='POST'){let body='';for await(const c of req)body+=c;const {table,payload}=JSON.parse(body);tables[table].set(payload.user_id,payload);await new Promise(r=>setTimeout(r,300));res.end(JSON.stringify({data:payload}));}else res.end(JSON.stringify({data:tables[url.searchParams.get('table')]?.get(url.searchParams.get('owner'))||null}));return;}
 const relative=url.pathname==='/'?'index.html':url.pathname.slice(1);const file=path.resolve(root,relative);if(!file.startsWith(root+path.sep)||!['.html','.js','.css','.svg'].includes(path.extname(file))){res.writeHead(404);res.end();return;}try{let text=fs.readFileSync(file,'utf8');if(relative==='index.html'){text=text.replace(/<script src="vendor\/supabase.js[^\"]*"><\/script>/,'').replace(/<script src="config.js[^\"]*"><\/script>/,'<script>('+mockClient.toString()+')();</script>');text=text.replace('<title>Cashcaval — Your net worth, clearly</title>','<title>Cashcaval — isolated browser test</title>');}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml'})[path.extname(file)]);res.end(text);}catch{res.writeHead(404);res.end();}}).listen(4174,'127.0.0.1',()=>console.log('Isolated QA: http://127.0.0.1:4174'));
